In [1]:
from sklearn import metrics
import pandas as pd
import numpy as np

def measure(test,prediction):
    recall = metrics.recall_score(test["label"],prediction)
    precision = metrics.precision_score(test["label"],prediction)
    f1_score = metrics.f1_score(test["label"],prediction)
    accuracy = metrics.accuracy_score(test["label"],prediction)

    print('Accuracy:',accuracy)
    print('Precision:',precision)
    print('Recall:',recall)
    print('f1 score:',f1_score)

    matrix = metrics.confusion_matrix(test["label"],prediction)
    print(matrix)

def predict(content):
    prediction = []
    for index, line in enumerate(content):
        line = line.strip()
        if "1" in line:
            prediction.append(1)
        elif "0" in line:
            prediction.append(0)
    return prediction

## Headlines Množica

In [2]:
test = pd.read_csv('../llama3/kontext_headlines_test.csv')

### LLama3

#### Ročni primeri

In [3]:
with open('../GPT_llama3_kontext/rocno_llama_headlines.txt', 'r', encoding='utf-8') as file:
    content = file.readlines()
prediction = predict(content)

measure(test,prediction)

Accuracy: 0.5666666666666667
Precision: 0.5714285714285714
Recall: 0.5333333333333333
f1 score: 0.5517241379310344
[[9 6]
 [7 8]]


#### GPT primeri

In [4]:
with open('../GPT_llama3_kontext/GPT_llama_headlines.txt', 'r', encoding='utf-8') as file:
    content = file.readlines()
prediction = predict(content)

measure(test,prediction)

Accuracy: 0.5333333333333333
Precision: 0.5454545454545454
Recall: 0.4
f1 score: 0.4615384615384615
[[10  5]
 [ 9  6]]


### GPT

#### Ročni primeri

In [5]:
with open('../GPT_llama3_kontext/rocno_GPT_headlines.txt', 'r', encoding='utf-8') as file:
    content = file.readlines()
prediction = predict(content)

measure(test,prediction)

Accuracy: 0.8333333333333334
Precision: 0.7777777777777778
Recall: 0.9333333333333333
f1 score: 0.8484848484848485
[[11  4]
 [ 1 14]]


#### GPT primeri

In [6]:
with open('../GPT_llama3_kontext/GPT_GPT_headlines.txt', 'r', encoding='utf-8') as file:
    content = file.readlines()
prediction = predict(content)

measure(test,prediction)

Accuracy: 0.6666666666666666
Precision: 0.7272727272727273
Recall: 0.5333333333333333
f1 score: 0.6153846153846153
[[12  3]
 [ 7  8]]
