In [1]:
from sklearn import metrics
import pandas as pd
import numpy as np

def measure(test,prediction):
    recall = metrics.recall_score(test["label"],prediction)
    precision = metrics.precision_score(test["label"],prediction)
    f1_score = metrics.f1_score(test["label"],prediction)
    accuracy = metrics.accuracy_score(test["label"],prediction)

    print('Accuracy:',accuracy)
    print('Precision:',precision)
    print('Recall:',recall)
    print('f1 score:',f1_score)

    matrix = metrics.confusion_matrix(test["label"],prediction)
    print(matrix)

def predict(content):
    prediction = []
    for index, line in enumerate(content):
        line = line.strip()
        if "1" in line:
            prediction.append(1)
        elif "0" in line:
            prediction.append(0)
    return prediction

## Reddit Množica

In [2]:
test = pd.read_csv('../llama3/kontext_reddit_test.csv')

### LLama3

#### Ročni primeri

In [3]:
with open('../GPT_llama3_kontext/rocno_llama_reddit.txt', 'r', encoding='utf-8') as file:
    content = file.readlines()
prediction = predict(content)

measure(test,prediction)

Accuracy: 0.6
Precision: 0.6666666666666666
Recall: 0.4
f1 score: 0.5
[[12  3]
 [ 9  6]]


#### GPT primeri

In [4]:
with open('../GPT_llama3_kontext/GPT_llama_reddit.txt', 'r', encoding='utf-8') as file:
    content = file.readlines()
prediction = predict(content)

measure(test,prediction)

Accuracy: 0.5333333333333333
Precision: 0.5714285714285714
Recall: 0.26666666666666666
f1 score: 0.36363636363636365
[[12  3]
 [11  4]]


### GPT

#### Ročni primeri

In [5]:
with open('../GPT_llama3_kontext/rocno_GPT_reddit.txt', 'r', encoding='utf-8') as file:
    content = file.readlines()
prediction = predict(content)

measure(test,prediction)

Accuracy: 0.7666666666666667
Precision: 0.7
Recall: 0.9333333333333333
f1 score: 0.8
[[ 9  6]
 [ 1 14]]


#### GPT primeri

In [6]:
with open('../GPT_llama3_kontext/GPT_GPT_reddit.txt', 'r', encoding='utf-8') as file:
    content = file.readlines()
prediction = predict(content)

measure(test,prediction)

Accuracy: 0.7666666666666667
Precision: 0.8333333333333334
Recall: 0.6666666666666666
f1 score: 0.7407407407407408
[[13  2]
 [ 5 10]]


#### Baseline

In [7]:
with open('../GPT_llama3_kontext/no_GPT_reddit.txt', 'r', encoding='utf-8') as file:
    content = file.readlines()
prediction = predict(content)

measure(test,prediction)

Accuracy: 0.7333333333333333
Precision: 0.7058823529411765
Recall: 0.8
f1 score: 0.7500000000000001
[[10  5]
 [ 3 12]]
