In [17]:
from sklearn import metrics
import pandas as pd
import numpy as np

def metric(test,prediction):
    recall = metrics.recall_score(test["label"],prediction)
    precision = metrics.precision_score(test["label"],prediction)
    f1_score = metrics.f1_score(test["label"],prediction)
    accuracy = metrics.accuracy_score(test["label"],prediction)
    loss = metrics.log_loss(test["label"],prediction)

    print('Loss:',loss)
    print('Accuracy:',accuracy)
    print('Precision:',precision)
    print('Recall:',recall)
    print('f1 score:',f1_score)

    kappa = metrics.cohen_kappa_score(test["label"],prediction)
    print('Cohens kappa: %f' % kappa)
    auc = metrics.roc_auc_score(test["label"],prediction)
    print('ROC AUC: %f' % auc)
    matrix = metrics.confusion_matrix(test["label"],prediction)
    print(matrix)
    

### Množica headlines

In [18]:
test = pd.read_csv('../data/headlines_test.csv')
with open('../training/headline_pred.txt', 'r') as file:
    content = file.readlines()
prediction = [int(line.strip()) for line in content]

In [19]:
metric(test,prediction)

Loss: 15.540834480143452
Accuracy: 0.5688329839273235
Precision: 0.529946303180504
Recall: 0.9303843364757071
f1 score: 0.6752631578947369
Cohens kappa: 0.158813
ROC AUC: 0.581510
[[ 345 1138]
 [  96 1283]]


### Množica headlines z razlagami

In [20]:
test = pd.read_csv('../data/headlines_test.csv')
with open('../training/headline_pred2.txt', 'r', encoding='utf-8') as file:
    content = file.readlines()
prediction = []
invalid_indexes = []

for index, line in enumerate(content):
    line = line.strip()
    if "1" in line:
        prediction.append(1)
    elif "0" in line:
        prediction.append(0)
    else:
        invalid_indexes.append(index)
print(invalid_indexes)
test = test.drop(invalid_indexes)

[]


In [21]:
metric(test,prediction)

Loss: 14.533324951446959
Accuracy: 0.596785464709993
Precision: 0.5481386392811296
Recall: 0.9289340101522843
f1 score: 0.6894510226049515
Cohens kappa: 0.211707
ROC AUC: 0.608432
[[ 427 1056]
 [  98 1281]]


### Množica reddit

In [22]:
test = pd.read_csv('../data/reddit_test.csv')
with open('../training/reddit_pred.txt', 'r') as file:
    content = file.readlines()
prediction = []
invalid_indexes = []

for index, line in enumerate(content):
    line = line.strip()
    if line == '0' or line == '1':
        prediction.append(int(line))
    else:
        invalid_indexes.append(index)
test = test.drop(invalid_indexes)

In [23]:
metric(test,prediction)

Loss: 15.507715391763014
Accuracy: 0.5697518443997317
Precision: 0.5718085106382979
Recall: 0.5737158105403602
f1 score: 0.5727605727605728
Cohens kappa: 0.139463
ROC AUC: 0.569730
[[839 644]
 [639 860]]


### Množica reddit z razlagami

In [24]:
test = pd.read_csv('../data/reddit_test.csv')
with open('../training/reddit_pred2.txt', 'r') as file:
    content = file.readlines()
prediction = []
invalid_indexes = []

for index, line in enumerate(content):
    line = line.strip()
    if '0' in line:
        prediction.append(0)
    elif '1' in line:
        prediction.append(1)
    else:
        invalid_indexes.append(index)
test = test.drop(invalid_indexes)

In [25]:
metric(test,prediction)

Loss: 16.027435308433905
Accuracy: 0.5553326646606486
Precision: 0.5632102272727273
Recall: 0.5258620689655172
f1 score: 0.5438957475994514
Cohens kappa: 0.111100
ROC AUC: 0.555581
[[868 615]
 [715 793]]
